source 'https://rubygems.org'

gem 'rake', '>=10.1.1'
gem 'ptools', '>=1.2.4'
gem 'os', '>=0.9.6'
gem 'r10k', '>=1.2.1'
gem 'vagrant-vmware-fusion', '>= 0.0.1'
source 'https://rubygems.org/'

gem 'jekyll', :git => 'git://github.com/puppetlabs/jekyll.git', :branch => 'puppetdocs'
gem 'maruku'
gem 'kramdown'
gem 'versionomy'
gem 'rack'
gem 'yard'
gem 'rdoc'
gem 'vlad'
gem 'vlad-git'
gem 'activerecord', '~>3'
gem 'ronn'
