mod 'puppetlabs-apache', :git => 'https://github.com/puppetlabs/puppetlabs-apache'
mod 'puppetlabs-stdlib', :git => 'https://github.com/puppetlabs/puppetlabs-stdlib'
mod 'puppetlabs-mysql', :git => 'https://github.com/puppetlabs/puppetlabs-mysql'
